<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0ab65520-f7b9-4496-90e5-a4e5b55858b0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlazorPro.BlazorSize" Version="8.0.0" />
    <PackageReference Include="MediatR" Version="12.3.0" />
    <PackageReference Include="MudBlazor" Version="6.20.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StravaClubStats.ServiceDefaults\StravaClubStats.ServiceDefaults.csproj" />
    <ProjectReference Include="..\StravaClubStatsEngine\StravaClubStatsEngine.csproj" />
    <ProjectReference Include="..\StravaStatsClubShared\StravaClubStatsShared.csproj" />
  </ItemGroup>

</Project>
